### ISSUE TITLE
Missing media files causing IOError

### ISSUE THREAD

**Issue by glutanimate** [rsimmons/anki-cropro#1]
Hi there!

Kudos first of all on writing this add-on! I could really see it coming in handy when handling external decks.

I ran into a small issue when trying to import from a deck that had been stripped of all media files (e.g. when leaving the corresponding checkmark out on an Anki apkg export).

Here's the associated error message:

```
Traceback (most recent call last):
  File "/home/glutanimate/cross-profile-decks/addons/Cross_Profile_Search_and_Import.py", line 297, in doImport
    addedFn = mw.col.media.addFile(fullfn)
  File "/home/anki_src/anki/media.py", line 138, in addFile
    return self.writeData(opath, open(opath, "rb").read())
IOError: [Errno 2] Datei oder Verzeichnis nicht gefunden: u'/home/glutanimate/cross-profile-decks/Storage/collection.media/2949423.jpg'
```

Please let me know if you need me to provide any more info.

**Comment by rsimmons** [comment]
Thanks for the report! I've put an updated version on AnkiWeb that fixes this.

**Comment by glutanimate** [comment]
I can confirm that everything is working fine now. Thanks again for the lightning-fast fix!
